export { default as logo } from './logo.svg'
export { default as search } from './search.svg'
export { default as arrowDown } from './arrowDown.svg'

export { default as card1 } from './card1.png'
export { default as card2 } from './card2.png'
export { default as card3 } from './card3.png'
export { default as card4 } from './card4.png'
export { default as card5 } from './card5.png'
export { default as card6 } from './card6.png'
export { default as card7 } from './card7.png'
export { default as card8 } from './card8.png'